services:
  web:
    image: patientor-frontend-dev
    build:
      context: ./patientor/
      dockerfile: dev.Dockerfile
      # WATCH DEVELOPMENT MODE
      # docker compose -f docker-compose.dev.yml watch
    develop:
      watch:
        - action: sync
          path: ./patientor/src
          target: usr/src/app/src
      # ignore:
      #   - node_modules/
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    container_name: patientor-frontend-container-dev

  server:
    image: patientor-backend-dev
    build:
      context: ./patientor-backend/
      dockerfile: dev.Dockerfile
    # volumes:
    # - ./patientor-backend/:/usr/src/app
    container_name: patientor-backend-container-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro # read-only
    ports:
      - 8080:80
    container_name: reverse-proxy-patientor-dev
    depends_on:
      - web
