services:
  web_prod:
    image: patientor-frontend-prod
    build:
      context: ./patientor/
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    container_name: patientor-frontend-container-prod

  server_prod:
    image: patientor-backend-prod
    build:
      context: ./patientor-backend/
      dockerfile: Dockerfile
    container_name: patientor-backend-container-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # read-only
    ports:
      - 8080:80
    container_name: reverse-proxy-patientor-prod
    depends_on:
      - web_prod
